# Generated by Django 3.0.4 on 2020-03-26 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='business_analyst',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='consultant',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_analyst',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='data_scientist',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='developer',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='international',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='mid_atlantic',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='midwest',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='northeast',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='pacific_northwest',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='south',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='southeast',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='southwest',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='west',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='within_US',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')]),
        ),
        migrations.CreateModel(
            name='certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SAS_base_programmer', models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')])),
                ('SAS_statistical_business_analyst', models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')])),
                ('Oracle_SQL', models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')])),
                ('NVIDIA_deep_learning_with_NLP', models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')])),
                ('Tableau', models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')])),
                ('INFORM_CAP_aCAP', models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')])),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Candidates.student')),
            ],
        ),
    ]
