# Generated by Django 3.0.4 on 2020-03-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0002_auto_20200326_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certification',
            old_name='ID',
            new_name='Student',
        ),
        migrations.AlterField(
            model_name='certification',
            name='INFORM_CAP_aCAP',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='NVIDIA_deep_learning_with_NLP',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='Oracle_SQL',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='SAS_base_programmer',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='SAS_statistical_business_analyst',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='certification',
            name='Tableau',
            field=models.BooleanField(),
        ),
    ]
