# Generated by Django 3.0.4 on 2020-03-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0003_auto_20200326_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='INFORM_CAP_aCAP',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='NVIDIA_deep_learning_with_NLP',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Oracle_SQL',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SAS_base_programmer',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='SAS_statistical_business_analyst',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='Tableau',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='certification',
        ),
    ]
