# Generated by Django 3.0.4 on 2020-03-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0005_auto_20200326_2234'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='ID',
            new_name='student_id',
        ),
        migrations.AddField(
            model_name='student',
            name='financial_services',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
        )
    ]
