# Generated by Django 3.0.4 on 2020-03-26 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0009_auto_20200326_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='analytics_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='total_professional_experience',
            field=models.IntegerField(default=0),
        ),
    ]
