# Generated by Django 3.0.4 on 2020-04-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0010_auto_20200326_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='hired',
            field=models.IntegerField(choices=[(None, ''), (0, 'No'), (1, 'Yes')], default=0),
        ),
    ]
