# Generated by Django 3.0.4 on 2020-04-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0012_student_picturelink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='picturelink',
        ),
    ]
