# Generated by Django 3.0.4 on 2020-04-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0013_remove_student_picturelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='picturelink',
            field=models.URLField(default=''),
        ),
    ]
