# Generated by Django 3.0.4 on 2020-04-21 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0017_remove_student_videolink'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='videolink',
            field=models.URLField(default='data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACoCAMAAABt9SM9AAAAA1BMVEUQDQgAKWjVAAAAR0lEQVR4nO3BAQEAAACCIP+vbkhAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO8GxYgAAb0jQ/cAAAAASUVORK5CYII='),
        ),
    ]
