# Generated by Django 3.0.4 on 2020-04-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0018_student_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='videolink',
            field=models.URLField(default='https://tshop.r10s.jp/hanjo/cabinet/c/imgrc0071257391.jpg?fitin=330:330'),
        ),
    ]
