# Generated by Django 3.0.4 on 2020-04-21 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0019_auto_20200421_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='videolink',
        ),
    ]
