# Generated by Django 3.0.4 on 2020-05-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Candidates', '0028_auto_20200522_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='posterlink',
            field=models.URLField(default=''),
        ),
    ]
