# Generated by Django 3.0.4 on 2020-05-17 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
